---
- name: Baseline Linux Server Provisioning
  hosts: all
  become: yes

  vars:
    pacotes_basicos:
      - vim
      - wget
      - curl
      - net-tools
      - unzip
      - bash-completion
      - tcpdump

  tasks:

  - name: Atualizar sistema
    yum:
      name: "*"
      state: latest

  - name: Instalar pacotes básicos
    yum:
      name: "{{ pacotes_basicos }}"
      state: present

  - name: Criar usuário padrão
    user:
      name: "{{ usuario_padrao }}"
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: Instalar Zabbix Agent
    yum:
      name: zabbix-agent
      state: present

  - name: Garantir que o serviço Zabbix esteja habilitado
    service:
      name: zabbix-agent
      state: started
      enabled: yes

  - name: Reiniciar SSH
    service:
      name: sshd
      state: restarted
